# Generated by Django 3.0.5 on 2021-04-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('pic', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField()),
                ('cars', models.ManyToManyField(to='mainapp.Car')),
            ],
        ),
    ]
