# Generated by Django 3.0.5 on 2021-04-29 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('denied', 'denied')], default='pending', max_length=10)),
                ('created_by', models.CharField(max_length=30)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Car')),
                ('dealership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Dealership')),
            ],
        ),
    ]
