const GET_CARS='GET_CARS';
/*
const AUTH_START='AUTH_START';
const AUTH_SUCCSESS='AUTH_SUCCSESS';
const AUTH_FAIL='AUTH_FAIL';
const AUTH_LOGOUT='AUTH_LOGOUT';

*/


export default GET_CARS;
export  const SET_TOKEN='SET_TOKEN';
export  const SET_CURRENT_USER='SET_CURRENT_USER';
export  const UNSET_CURRENT_USER='UNSET_CURRENT_USER'; 
export  const CREATE_USER_SUBMITTED='CREATE_USER_SUBMITTED'
export  const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export  const CREATE_USER_ERROR = "CREATE_USER_ERROR";