const GET_CARS='GET_CARS';
/*
const AUTH_START='AUTH_START';
const AUTH_SUCCSESS='AUTH_SUCCSESS';
const AUTH_FAIL='AUTH_FAIL';
const AUTH_LOGOUT='AUTH_LOGOUT';

*/


export default GET_CARS;
export  const SET_TOKEN='SET_TOKEN';
export  const SET_CURRENT_USER='SET_CURRENT_USER';
export  const SET_LOADING='SET_LOADING';
export  const UNSET_CURRENT_USER='UNSET_CURRENT_USER';
export  const UNSET_LOADING='UNSET_LOADING'; 
export  const CREATE_USER_SUBMITTED='CREATE_USER_SUBMITTED'
export  const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export  const CREATE_USER_ERROR = "CREATE_USER_ERROR"; 
export  const GET_DEALERSHIPS="GET_DEALERSHIPS";
export  const GET_CAR="GET_CAR";
export  const GET_DEALERSHIP="GET_DEALERSHIP" 
export const MAKE_BOOKING="MAKE_BOOKING"
export const GET_BOOKINGS="GET_BOOKINGS"
export const CONFIRM_BOOKING="CONFIRM_BOOKING"
export const CANCEL_BOOKING="CANCEL_BOOKING"
export const EDIT_PROFILE="EDIT_PROFILE"
export const GET_CUSTOMER="GET_CUSTOMER"
export const GET_TOTAL_SALES="GET_TOTAL_SALES"
export const GET_DEALERS_SALES="GET_DEALERS_SALES"
export const GET_REPORTS="GET_REPORTS"
export const ADD_REPORTS="ADD_REPORTS"